import type { Metadata } from "next";

import { Layout } from "@/components/Layout";
import { ThemeProvider } from "@/providers/ThemeProvider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      suppressHydrationWarning
      className='h-full antialiased'
    >
      <body
        className="
          min-h-screen
          flex justify-center items-center
          p-6
          bg-[url('/assets/bg-mobile-light.jpg')] md:bg-[url('/assets/bg-desktop-light.jpg')] bg-cover
          dark:bg-[url('/assets/bg-mobile.jpg')] md:dark:bg-[url('/assets/bg-desktop.jpg')]
        "
      >
        <ThemeProvider>
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
