import type { Metadata } from "next";

import { Layout } from "@/components/Layout";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className='h-full antialiased'
    >
      <body
        className="
          min-h-screen
          flex justify-center items-center
          p-6
          bg-[url('/assets/bg-mobile-light.jpg')] md:bg-[url('/assets/bg-desktop-light.jpg')] bg-cover
        "
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
